### ISSUE TITLE
When tried to add JSX in index.js file, it failed with error.

### ISSUE THREAD

**Issue by namokumar** [lalitkumarthakur/udemy-reactjs#18]
In index.js file, we usually link app.js and that 'app.js' behaves like our home page. But, I don't want that. I want to have my 'home page contents' into index.js through inline components. 

I tried doing that but it failed giving this erro - 

" react-dom.development.js:29674 Uncaught Error: Target container is not a DOM element.
    at render (react-dom.development.js:29674:1)
    at MainBody (index.js:8:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at recoverFromConcurrentError (react-dom.development.js:25850:1) "
    

And on the homescreen, it displays body backgroud color but nothing except that. 
check this image - 
![Screenshot from 2023-12-05 17-18-03](https://github.com/lalitkumarthakur/udemy-reactjs/assets/45649399/94c1b73f-9854-4ade-a046-8ec1c1d4d37c)

here how the order should be -

-------------------------------------------------------------------------------------body (index.js)------------------------------------------------------------- 
 ***heading***
***paragraph***
***more content***

   ------------------------------Parent component 1(app.js)--------------------------
  | content                                                                                                      |
  | content                                                                                                      |
  | content                                                                                                      |                           
  |    --------------component 1(any component)--------------                        |
  |   | component                                                                 |                       |                   
  |   | component                                                                 |                       |
  | -------------------------------------------------------------------------|                        | 

Please help.

**Comment by namokumar** [comment]
The code is commented in index.js file. Please uncomment and fix the issue

**Comment by SabAlej** [comment]
Hello @lalitkumarthakur ! Sorrry, I couldn't run it locally because I can't find the package.json 😅. But i can say that in your functional component you are using **_render_** instead of **_return_**. I think that if you change it, you won't have the error. Like this:
[MainBody](https://user-45aefbe1-ea24-4e4b-afff-aa104f8db6b3-qskcnsmieq-uc.a.run.app/?p=f32247bcfb)
Hope this helps 🌻
